name: otel-profiling-agent

on:
  push:
    branches: [main]
  pull_request:
    branches: ["**"]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      max-parallel: 2
      matrix:
        go: ["stable"]
    steps:
    - name: Install dependencies
      run: sudo apt-get install -y llvm clang dwz cmake curl unzip
    - name: Install Zydis
      shell: bash
      run: |
        cd /tmp
        git clone --depth 1 --branch v3.1.0 --recursive https://github.com/zyantific/zydis.git
        cd zydis
        rm -rf build
        mkdir build
        cd build
        cmake -DZYDIS_BUILD_EXAMPLES=OFF ..
        make -j$(nproc)
        sudo make install
        cd zycore
        sudo make install
    - name: Set up Go ${{matrix.go}}
      uses: actions/setup-go@v5
      with:
        go-version: ${{matrix.go}}
        check-latest: true
        cache-dependency-path: |
          go.sum
      id: go
    - name: Check out
      uses: actions/checkout@v4
    - name: Linter
      run: |
        go version
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.56.2
        make lint

  test:
    name: Test
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: true
      max-parallel: 2
      matrix:
        go: ["stable"]
    steps:
    - name: Install dependencies
      run: sudo apt-get install -y llvm clang-16 dwz cmake curl unzip
    - name: Install Zydis
      shell: bash
      run: |
        cd /tmp
        git clone --depth 1 --branch v3.1.0 --recursive https://github.com/zyantific/zydis.git
        cd zydis
        rm -rf build
        mkdir build
        cd build
        cmake -DZYDIS_BUILD_EXAMPLES=OFF ..
        make -j$(nproc)
        sudo make install
        cd zycore
        sudo make install
    - name: Set up Go ${{matrix.go}}
      uses: actions/setup-go@v5
      with:
        go-version: ${{matrix.go}}
        check-latest: true
        cache-dependency-path: |
          go.sum
      id: go
    - name: Check out
      uses: actions/checkout@v4
    - name: Build
      run: |
        echo $PATH
        make test
    - name: Tests
      run: |
        make test
